spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
  application:
    name: oauth2-authorization-server

server:
  port: 9000

logging:
  level:
    "[org.springframework.security]": DEBUG
    "[org.springframework.security.oauth2]": DEBUG
    "[org.springframework.security.oauth2.jwt]": DEBUG
    "[org.springframework.web.client]": DEBUG